name: fluxoMind
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.10
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore:
  photo_view: ^0.10.2
  carousel_slider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/Atv1/
